apiVersion: v1
kind: Pod
metadata:
  name: jon-test-pod
spec:
  containers:
  - name: otel-span-generator
    image: jontg/otel-span-generator
    env:
    - name: OTLP_GRPC_ENDPOINT
      value: opentelemetry-collector.opentelemetry.svc:4317
